#PARAM MONDE

CELL_SIZE = 25
WIDTH = 20
HEIGHT = 20
#PARAM POPULATION
NB_TUNA: int = 10
NB_SHARK: int = 5

#PARAM REPRODUCTION
TUNA_REPRODUCTION_TIME: int = 8
SHARK_REPRODUCTION_TIME: int = 12

#PARAM ENERGY
SHARK_INITIAL_ENERGY: int = 10
SHARK_ENERGY_GAIN: int = 7